Repository yanyongyu/githubkit, pull requests merged in 2023-04, with the labels that each got.

#24 Add support for REST-API-VERSION based on the used schema
  codegen/__init__.py
  codegen/config.py
  codegen/templates/client/_request.py.jinja
  codegen/templates/client/client.py.jinja
  pyproject.toml
Labels: enhancement

#26 Fix: Remove `UNSET` objects from lists
  githubkit/utils.py
Labels: bug

#30 Fix: auto-merge commit_title/commit_message type
  pyproject.toml
Labels: schema, Rest API, WebHook

#32 Fix: org company and email can be null
  githubkit/rest/models.py
  githubkit/rest/types.py
  pyproject.toml
Labels: bug, schema, Rest API
