Repository yanyongyu/githubkit, pull requests merged in 2024-07, with the labels that each got.

#115 Feature: support oauth token auth
  README.md
  envs/pydantic-v1/poetry.lock
  envs/pydantic-v2/poetry.lock
  envs/test/poetry.lock
  githubkit/__init__.py
  githubkit/auth/__init__.py
  githubkit/auth/oauth.py
Labels: enhancement

#118 Fix: Tolerate any string values in github app events array schema
  pyproject.toml
Labels: bug, schema, WebHook

#120 Docs: update type hints in examples
  README.md
Labels: documentation

#121 Feature: add graphql pagination support
  README.md
  githubkit/exception.py
  githubkit/github.py
  githubkit/graphql/__init__.py
  githubkit/graphql/paginator.py
  tests/test_graphql/test_graphql.py
Labels: enhancement, GraphQL
