Repository yanyongyu/githubkit, pull requests merged in 2024-09, with the labels that each got.

#128 Feature: improve refresh token usage and docs
  README.md
  githubkit/auth/oauth.py
Labels: documentation, enhancement

#129 Feature: support app jwt auth using client id
  githubkit/auth/app.py
Labels: enhancement

#130 Fix: oauth flow anext compatibility
  githubkit/auth/oauth.py
Labels: bug

#131 Fix: model list schema constraints error when using Pydantic V1
  codegen/parser/schemas/schema.py
Labels: bug, schema

#134 Fix: diff-entry's blob_url and raw_url may be null
  githubkit/versions/ghec_v2022_11_28/models/group_0213.py
  githubkit/versions/ghec_v2022_11_28/types/group_0213.py
  githubkit/versions/v2022_11_28/models/group_0190.py
  githubkit/versions/v2022_11_28/types/group_0190.py
  pyproject.toml
Labels: bug, schema, Rest API

#135 Fix: ghes graphql endpoint error
  README.md
  githubkit/graphql/__init__.py
  tests/test_graphql/test_endpoint.py
Labels: bug, GraphQL

#142 Docs: add unit test example
  README.md
  tests/test_unit_test/fake_response.json
  tests/test_unit_test/test_unit_test.py
Labels: documentation
