Repository yanyongyu/githubkit, pull requests merged in 2025-06, with the labels that each got.

#219 Fix: app auth token expiration edge case
  githubkit/auth/app.py
Labels: bug

#225 Feature: support streaming response data
  codegen/templates/rest/_param.py.jinja
  codegen/templates/rest/_request.py.jinja
  githubkit/core.py
  githubkit/response.py
  tests/test_rest/test_call.py
Labels: enhancement, Rest API

#227 Feature: support custom proxy
  docs/usage/configuration.md
  githubkit/config.py
  githubkit/core.py
  githubkit/github.py
  githubkit/typing.py
Labels: enhancement

#228 Docs: add streaming response guide
  docs/usage/rest-api.md
Labels: documentation
