Repository yanyongyu/githubkit, pull requests merged in 2025-01, with the labels that each got.

#174 Fix: workflow_run pull_requests id/number types
  githubkit/versions/ghec_v2022_11_28/models/group_0266.py
  githubkit/versions/ghec_v2022_11_28/models/group_0836.py
  githubkit/versions/ghec_v2022_11_28/models/group_0837.py
  githubkit/versions/ghec_v2022_11_28/models/group_0838.py
  githubkit/versions/ghec_v2022_11_28/types/group_0266.py
  githubkit/versions/ghec_v2022_11_28/types/group_0836.py
  githubkit/versions/ghec_v2022_11_28/types/group_0837.py
  githubkit/versions/ghec_v2022_11_28/types/group_0838.py
  githubkit/versions/v2022_11_28/models/group_0229.py
  githubkit/versions/v2022_11_28/models/group_0778.py
  githubkit/versions/v2022_11_28/models/group_0779.py
  githubkit/versions/v2022_11_28/models/group_0780.py
  githubkit/versions/v2022_11_28/types/group_0229.py
  githubkit/versions/v2022_11_28/types/group_0778.py
  githubkit/versions/v2022_11_28/types/group_0779.py
  githubkit/versions/v2022_11_28/types/group_0780.py
  pyproject.toml
Labels: bug, schema, WebHook

#180 Docs: update response types for json type inspect
  docs/usage/authentication.md
  docs/usage/rest-api.md
  docs/usage/unit-test.md
Labels: documentation

#181 Fix: deployment payload object allow additional property
  githubkit/rest/__init__.py
  githubkit/versions/ghec_v2022_11_28/models/__init__.py
  githubkit/versions/ghec_v2022_11_28/models/group_0540.py
  githubkit/versions/ghec_v2022_11_28/models/group_0545.py
  githubkit/versions/ghec_v2022_11_28/types/__init__.py
  githubkit/versions/ghec_v2022_11_28/types/group_0540.py
  githubkit/versions/latest/models.py
  githubkit/versions/latest/types.py
  githubkit/versions/v2022_11_28/models/__init__.py
  githubkit/versions/v2022_11_28/models/group_0482.py
  githubkit/versions/v2022_11_28/models/group_0487.py
  githubkit/versions/v2022_11_28/types/__init__.py
  githubkit/versions/v2022_11_28/types/group_0482.py
  pyproject.toml
Labels: bug, schema, WebHook

#186 Fix: httpx query param type error
  githubkit/typing.py
Labels: bug
