Repository yanyongyu/githubkit, pull requests merged in 2025-04, with the labels that each got.

#202 Fix: PR Head field type error
  githubkit/versions/ghec_v2022_11_28/models/group_0383.py
  githubkit/versions/ghec_v2022_11_28/types/group_0383.py
  githubkit/versions/v2022_11_28/models/group_0343.py
  githubkit/versions/v2022_11_28/types/group_0343.py
  pyproject.toml
Labels: bug, schema, Rest API

#201 Feature: make GitUser's `date` field to be date-time
  githubkit/versions/ghec_v2022_11_28/models/group_0261.py
  githubkit/versions/ghec_v2022_11_28/types/group_0261.py
  githubkit/versions/v2022_11_28/models/group_0221.py
  githubkit/versions/v2022_11_28/types/group_0221.py
  pyproject.toml
Labels: enhancement, schema, Rest API

#204 Fix: add missing enum values for dependabot and code scanning alerts
  pyproject.toml
Labels: bug, schema, Rest API

#209 Feature: add httpx `verify` config
  docs/usage/configuration.md
  githubkit/config.py
  githubkit/core.py
  githubkit/github.py
Labels: enhancement

#210 Docs: add more info to rest api methods' docstring
  codegen/pyproject.toml
  codegen/templates/rest/_docstring.py.jinja
  codegen/templates/rest/client.py.jinja
  pyproject.toml
  scripts/run-codegen.sh
Labels: documentation, enhancement

#212 Fix: rest paginator iteration error
  githubkit/rest/paginator.py
  tests/test_rest/test_call.py
Labels: bug, Rest API
